set nocp
set encoding=utf-8
set fileencoding=utf-8

nnoremap <SPACE> <Nop>
let mapleader=" "

syntax on
set hlsearch

set spell spelllang=en_us

set lpl

set t_Co=256
colorscheme desert256

set pastetoggle=<f5> "for better pasting from clipboard http://stackoverflow.com/questions/9677475/how-can-i-do-the-paste-in-vim-without-troubled-by-indent-issue
set autoindent "conflict with set paste, which effectively turn off autoindent, so use the pastetoggle above to turn on then paste and then turn back off

let g:html_minlines = 1000
